# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'FacialAnalysis' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FacialAnalysis
	pod 'VisionLab', :git => 'https://github.com/cocoa-ai/VisionLab', :branch => 'master'

end
